version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: makan_db
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
  pg-admin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: user-name@domain-name.com
      PGADMIN_DEFAULT_PASSWORD: 12345qwe
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "8888:80"
volumes:
  data:
  pgadmin-data: